### ISSUE TITLE
User indentation preferences

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/cil-mode#21]
We should allow (through customization or other way) the user to set his preference on indentation (length and tabs / spaces).

**Comment by CyberShadow** [comment]
Any reason why the default indentation mode doesn't match ildasm output? ildasm uses 2 spaces as indentation size, whereas cil-mode uses 4.

**Comment by ForNeVeR** [comment]
That's just my own preferred setting. Please, feel free to create PR and change the settings. I think that it'd be better to follow `ildasm` defaults than my own personal preference, so I would accept that PR.

(But it would be even better to add customization options so everyone could make their own choice.)
